### PR TITLE
fix this

### PR DESCRIPTION
**Pull request by Nagol12344**

### CODE REVIEW

**Comment by AngelGonePro** [comment]
I'm not deleting everything thank you very much.

**Comment by Nagol12344** [comment]
This is fucking spyware and shouldnt exist, your giving your users data to a third party so you can stop them from leaving your discord server. Please rethink your actions and delete this, and your vaultcord account.

**Comment by AngelGonePro** [comment]
Yea well, you make a better one we can use.
Then I won't have to use it.

**Comment by Nagol12344** [comment]
...
________________________________

**Pull request closed without merging**
